# Generated by Django 5.1.6 on 2026-01-15 20:06

from django.db import migrations


def update_superuser_roles(apps, schema_editor):
    """Update role to 'admin' for all existing superusers"""
    User = apps.get_model('api', 'User')
    User.objects.filter(is_superuser=True).update(role='admin')


def reverse_update_superuser_roles(apps, schema_editor):
    """Reverse function - no action needed"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_address_user_phone_number_user_profile_picture'),
    ]

    operations = [
        migrations.RunPython(update_superuser_roles, reverse_update_superuser_roles),
    ]
