# Generated by Django 6.0.1 on 2026-01-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='store_description',
            field=models.TextField(blank=True, help_text='Store description for sellers', null=True),
        ),
    ]
